version: '3.3'

services:
  fastapi-app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app  # Mount the app folder for local development
    environment:
      - VIRTUAL_ENV=/app/venv  # Set virtual environment path
    command: /app/venv/bin/uvicorn main:app --host 0.0.0.0 --port 8000

